export const copy = {
  name: 'Konkan Soil Intelligence',
  tagline: 'Soil suitability intelligence for Konkan agriculture',
  region: 'Konkan region · Maharashtra',
  view: 'Soil report',
  eyebrow: 'REGIONAL SOIL ASSESSMENT',
  title: 'A closer look at your soil.',
  subtitle: 'Konkan coast, Maharashtra',
  crop: 'Crop',
  crops: { Mango: 'Mango', Cashew: 'Cashew', Rice: 'Rice' },
  demo: 'Demonstration · Mock data',
  map: 'Konkan soil selection map',
  mapLoading: 'Loading regional map…',
  mapError: 'The map could not load. Please refresh to try again.',
  mapHint: 'Click the map to select a point · Ctrl + scroll to zoom',
  reset: 'Reset map view',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  north: 'N',
  coverage: 'Konkan coastal region',
  report: 'Soil report',
  selected: 'Selected location',
  summary: 'Crop suitability summary',
  data: 'Soil properties',
  measured: 'Modeled values',
  source: 'Soil survey data — modeled, static',
  estimated: 'Estimated from nearby area',
  loading: 'Assessing soil at this location…',
  empty: 'No soil data available for this location — try a nearby point',
  error: 'The soil report could not load. Please try another point.',
  favorable: 'Favorable',
  attention: 'Needs attention',
  unsuitable: 'Not favorable',
  phGood: 'Soil pH is well suited for this crop.',
  phPoor: 'Soil pH is outside the preferred range for this crop.',
  organic: 'Organic matter is moderate.',
  water: 'Soil holds water well but may drain slowly.',
  drainage: 'Good drainage is important for healthy root growth.',
  riceWater: 'Water retention is favorable for rice cultivation.',
  labels: { ph: 'pH', carbon: 'Organic Carbon', texture: 'Texture', fractions: 'Clay / Sand / Silt', density: 'Bulk Density' },
  units: { ph: 'pH units', percent: '%', density: 'g/cm³' },
  textures: { clayLoam: 'Clay Loam', sandyLoam: 'Sandy Loam' },
  fractions: { clay: 'Clay', sand: 'Sand', silt: 'Silt' },
  footer: 'Konkan Soil Intelligence',
  footerNote: 'Regional assessment · Soil only',
  mapAttribution: '© OpenStreetMap contributors',
  titleMeta: 'Soil Report — Konkan Soil Intelligence',
  descriptionMeta: 'Explore modeled soil properties and crop suitability for Mango, Cashew and Rice along the Konkan coast of Maharashtra.',
};
export type Crop = keyof typeof copy.crops;
export const crops: Crop[] = ['Mango', 'Cashew', 'Rice'];